#! /bin/sh

bspc config border_width        2
bspc config window_gap         14

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config top_padding 24

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config normal_border_color '#282828'
bspc config focused_border_color '#0b709f'
bspc config presel_border_color '#10a2e7'
bspc config normal_sticky_border_color '#1d2021'
bspc config focused_sticky_border_color '#d5c4a1'
bspc config urgent_border_color '#cc241d'

compton -b -c &
sh /home/vlad/.config/bspwm/java_nonreparenting_wm_hack.sh
